baseURL = "http://example.org/"
languageCode = "en-us"

title = "sttp://"

theme = "nocode"

[params]
  description = "secure-thought-transfer-protocol"

sectionPagesMenu = "main"

[menu]
  [[menu.main]]
    name = "Writing"
    url = "/writing/"
    weight = 1
  [[menu.main]]
    name = "Reading"
    url = "/reading/"
    weight = 2
  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 3

copyright = 'This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License.'

[author]
  name = 'My Name Here'