baseURL = "http://example.org/"
languageCode = "en-us"

title = "sttp://"
theme = "nocode"

[menu]
  [[menu.main]]
    name = "Writing"
    url = "/writing/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/"
    weight = 2
