name = 'sttp'
license = 'MIT'
licenselink = 'https://github.com/hrmnjt/sttp/LICENSE'
description = 'theme for hrmnjt.dev'

homepage = 'https://github.com/hrmnjt/sttp'

[author]
  name = 'hrmnjt'
  homepage = 'www.hrmnjt.dev'
