name = "nocode"
license = "MIT"
licenselink = "https://github.com/hrmnjt/sttp/themes/nocode/blob/master/LICENSE"
description = ""
homepage = ""
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "hrmnjt"
  homepage = ""
